services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-finder-api
    environment:
      GIN_MODE: release
    ports:
      - "8080:8080"
    restart: unless-stopped


networks:
  default:
    name: email-finder-network